/****************************************************************
DO NOT EDIT THIS FILE
Configure the Lodout in config\loadout.sqf
****************************************************************/

diag_log "Init - executing initLoadout.sqf"; // Reporting. Do NOT edit/remove

private ["_unit","_unitString","_setLoadout","_defaultItems"];
_unit = player;

if (!local _unit) exitWith {};

_unitString =  toLower(roleDescription _unit);

_setLoadout = [_unit,_unitString] execVM "config\loadout.sqf"; waitUntil {scriptDone _setLoadout};

if (mod_ACE3) then { // ACE3 items added by default
	//_defaultItems = ["ACE_EarPlugs","ACE_CableTie","ace_mapTools","ACE_IR_Strobe_Item"];
	_defaultItems = ["ACE_EarPlugs"];
	{
		_unit removeItems _x;
		_unit addItemToUniform _x;
	} forEach _defaultItems;
};
