/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initTPL.sqf"; // Reporting. Do NOT edit/remove

waitUntil {(setLoadout)};
if (mod_ACE3 && !isCurator) then {
	if ( vehicle player == player ) then {
		[player, currentWeapon player, currentMuzzle player] call ACE_SafeMode_fnc_lockSafety;
	};
};
if (mod_Ares) then {
	qipTPL_initAres = [] execVM "init\ares\initAres.sqf";
};
