/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initAres.sqf"; // Reporting. Do NOT edit/remove

#include "loadout_transfer.sqf"
