/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

["Arsenal", "LT Load", {[_this select 1,false,false,false,true,true] call LT_fnc_LTaction;}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "LT Arsenal", {[_this select 1,false,true,false,false,true] call LT_fnc_LTaction;}] call Ares_fnc_RegisterCustomModule;
