/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/


if (!mod_ACE3) then {
	[] execVM "3rdPartyScripts\NRE_earplugs.sqf"; // Earplugs
	[] execVM "3rdPartyScripts\zlt_fieldrepair.sqf"; // Realistic repair script
};
[] execVM "3rdPartyScripts\IntLight.sqf"; // Interior Lighting
[] execVM "3rdPartyScripts\zlt_fastrope.sqf"; // Helicopter fastrope script by zealot111
[] execVM "3rdPartyScripts\setPlayersRaitingToMax.sqf"; // Disable Friendly Fire Penalties - Credits: Rik (PhanTactical)
if (qipTPL_coldWeather) then {
	[] execVM "3rdPartyScripts\breathfog.sqf";
};
