/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

["Arsenal", "XLA Arsenal (Full)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_ALL.sqf";}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "XLA Arsenal (rearm)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_allowEquipped.sqf";}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "XLA Arsenal (BLU)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_BLU_SHARED.sqf";}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "XLA Arsenal (OPF)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_OPF_SHARED.sqf";}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "XLA Arsenal (IND)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_IND_SHARED.sqf";}] call Ares_fnc_RegisterCustomModule;
["Arsenal", "XLA Arsenal (CIV)", {[_this select 1] execVM "init\ares\XLA_Arsenal\XLA_arsenal_CIV.sqf";}] call Ares_fnc_RegisterCustomModule;
